#!/bin/sh
#
# runs DataImporter to populate a jcms target database with content from a jcms source database.
# example: ./dataimporter
#

dropdb wppi
createdb -O jcms wppi
psql -f jcms-schema.sql wppi

java -cp classes:/home/java/jcms-dev/classes:/usr/share/java/postgresql-jdbc.jar:/usr/local/lib/jtds.jar  net.ims.jcms.tools.DataImporter

