<%@ page contentType="application/rss+xml; charset=UTF-8" language="java" %><%@ page import="net.ims.jcms.*, net.ims.jcms.extras.*, java.sql.Date, java.util.*, java.text.*" %><?xml version="1.0" encoding="UTF-8"?><%

  // overall site settings
  String siteName = Setting.getString(application, "site_name");
  String copyrightText = Setting.getString(application, "site_copyrighttext");
  String siteHost = request.getServerName()+application.getContextPath();

  // get time zone and locale from web.xml parameters
  String timezone = DB.getTimeZone(application);
  String siteLanguage = application.getInitParameter("site.language");
  String siteCountry = application.getInitParameter("site.country");

  // site time zone, for formatting, etc.
  TimeZone tz = TimeZone.getTimeZone(timezone);

  // site locale, used various places, set in web.xml
  Locale locale = null;
  if (siteLanguage==null) {
    locale = Locale.getDefault();
  } else if (siteCountry==null) {
    locale = new Locale(siteLanguage);
  } else {
    locale = new Locale(siteLanguage, siteCountry);
  }

  // format for displaying dates in RSS
  SimpleDateFormat dateFormat = new SimpleDateFormat(Setting.getString(application,"calendar_date_format"), locale);

  // format for passing today's date
  SimpleDateFormat todayFormat = new SimpleDateFormat("yyyy-MM-dd");

  // get today
  Calendar calendar = Calendar.getInstance(tz, locale); // dates
  String today = todayFormat.format(calendar.getTime());

  // get the RSS events
  Event[] events = Event.getForRSS(application, today);
%>
<!-- RSS generated by <%=siteName%> on <%=today%> -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title><%=Util.rssClean(siteName)%> Calendar</title>
    <description><%=Util.rssClean(siteName)%> Calendar</description>
    <link>http://<%=request.getServerName()%><%=application.getContextPath()%>/</link>
    <atom:link href="http://<%=siteHost%>/calendar-rss.jsp" rel="self" type="application/rss+xml"/>
    <language><%=locale.getLanguage()%>-<%=locale.getCountry()%></language>
    <copyright>Copyright <%=calendar.get(Calendar.YEAR)%> <%=Util.rssClean(copyrightText)%></copyright>
    <generator>IMS Neptune</generator>
      <% for (int i=0; i<events.length; i++) { %>
      <item>
        <title><%=Util.rssClean(events[i].title)%> - <%=dateFormat.format(events[i].date)%> <%=Util.rssClean(events[i].time)%></title>
        <% if (events[i].url!=null && events[i].url.startsWith("http")) { %><link><%=events[i].url%></link><% } else if (events[i].url!=null) { %><link>http://<%=siteHost%><%=events[i].url%></link><% } %>
        <% if (events[i].description!=null) { %><description><%=Util.rssClean(events[i].description)%></description><% } %>
        <% if (events[i].url!=null && events[i].url.startsWith("http")) { %><guid isPermaLink="true"><%=events[i].url%></guid><% } else if (events[i].url!=null) { %><guid isPermaLink="true">http://<%=siteHost%><%=events[i].url%></guid><% } %>
      </item>
      <% } %>
  </channel>
</rss>
