<%@ page contentType="application/rss+xml; charset=UTF-8" language="java" %><%@ page import="net.ims.jcms.*,net.ims.jcms.extras.*,java.sql.Date,java.util.*,java.text.*" %><?xml version="1.0" encoding="UTF-8"?><%
/**
 * Comments RSS feed, requires cid
 */

// overall site settings
String siteName = Setting.getString(application, "site_name");
String copyrightText = Setting.getString(application, "site_copyrighttext");
String siteHost = request.getServerName()+application.getContextPath();

// get time zone and locale from web.xml parameters
String timezone = DB.getTimeZone(application);
String siteLanguage = application.getInitParameter("site.language");
String siteCountry = application.getInitParameter("site.country");
  
// site time zone, for formatting, etc.
TimeZone tz = TimeZone.getTimeZone(timezone);
  
// site locale, used various places, set in web.xml
Locale locale = null;
if (siteLanguage==null) {
  locale = Locale.getDefault();
} else if (siteCountry==null) {
  locale = new Locale(siteLanguage);
} else {
  locale = new Locale(siteLanguage, siteCountry);
}

// format for passing today's date
SimpleDateFormat todayFormat = new SimpleDateFormat("yyyy-MM-dd");

// date format for posted date/time
java.text.SimpleDateFormat commentsDateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
String dateformat = Setting.getString(application,"comments_dateformat");
if (dateformat.length()>0) commentsDateFormat = new java.text.SimpleDateFormat(dateformat);
  
// use basic date format
SimpleDateFormat pubDateFormat = new SimpleDateFormat("E, dd MMM yyyy hh:mm:ss z");

// get today
Calendar calendar = Calendar.getInstance(tz, locale); // dates
String today = todayFormat.format(calendar.getTime());

// comments are linked to a content item
int cid = Util.getInt(request, "cid");
if (cid==0) return;  

// page is passed in as well for context
Page p = new Page();
if (request.getParameter("pid")!=null) {
  int pid = Util.getInt(request, "pid");
  p = new Page(application,pid);
}

// as well as node
int nid = Util.getInt(request, "nid");

// get all the comments, newest first
Comment comments[] = Comment.getAllReversed(application, cid);

if (comments.length>0) {
%>
<!-- Comments RSS generated by <%=siteName%> on <%=today%> -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Comments posted to <%=p.title%> on <%=siteName%></title>
    <description>Comments posted to <%=p.title%> on <%=siteName%></description>
    <link>http://<%=siteHost%>/index.jsp?nid=<%=nid%></link>
    <atom:link href="http://<%=siteHost%>/comments-rss.jsp?pid=<%=p.pid%>&amp;cid=<%=cid%>&amp;nid=<%=nid%>" rel="self" type="application/rss+xml"/>
    <language><%=locale.getLanguage()%>-<%=locale.getCountry()%></language>
    <copyright>Copyright <%=calendar.get(Calendar.YEAR)%> <%=Util.rssClean(copyrightText)%></copyright>
    <generator>IMS Neptune</generator>
    <% for (int i=0; i<comments.length; i++) { %>
      <item>
        <title><%=Util.rssClean(comments[i].name+", "+comments[i].location)%> [<%=commentsDateFormat.format(comments[i].timeposted)%>]</title>
        <description><%=Util.rssClean(comments[i].comment)%></description>
        <link>http://<%=siteHost%>/index.jsp?nid=<%=nid%>#<%=comments[i].comment_id%></link>
        <guid isPermaLink="false">http://<%=siteHost%>/index.jsp?nid=<%=nid%>#<%=comments[i].comment_id%></guid>
      </item>
    <% } %>
  </channel>
</rss>
<%
}
%>
