<%@ page contentType="rss+xml; charset=UTF-8" language="java" %><%@ page import="net.ims.jcms.*, java.util.*, java.io.*, java.text.SimpleDateFormat" %><?xml version="1.0" encoding="UTF-8"?><%

  // overall site settings
  String siteName = Setting.getString(application, "site_name");
  String copyrightText = Setting.getString(application, "site_copyrighttext");
  String siteHost = request.getServerName()+application.getContextPath();

  // site time zone, used for timestamp formatting, set in web.xml
  TimeZone tz = TimeZone.getTimeZone(DB.getTimeZone(application));

  // site locale, used various places, set in web.xml
  Locale locale = Locale.getDefault();
  if (application.getInitParameter("site.language")!=null) {
    if (application.getInitParameter("site.country")!=null) {
      locale = new Locale(application.getInitParameter("site.language"), application.getInitParameter("site.country"));
    } else {
      locale = new Locale(application.getInitParameter("site.language"));
    }
  }

  Calendar calendar = Calendar.getInstance(tz, locale); // dates

  // use basic date format
  SimpleDateFormat pubDateFormat = new SimpleDateFormat("E, dd MMM yyyy hh:mm:ss z");
  
  // only show nodes visible to public (default access user)
  AccessUser au = Util.getDefaultAccessUser(application);

  // speed up if access not in use
  boolean accessEnabled = AccessRole.nodeCount(application)>0;
%>
<!-- RSS generated by <%=siteName%> on <%=new Date()%> -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title><%=Util.rssClean(siteName)%></title>
    <description><%=Util.rssClean(siteName)%></description>
    <link>http://<%=request.getServerName()%><%=application.getContextPath()%>/</link>
    <atom:link href="http://<%=siteHost%>/rss.jsp" rel="self" type="application/rss+xml"/>
    <language><%=locale.getLanguage()%>-<%=locale.getCountry()%></language>
    <copyright>Copyright <%=calendar.get(Calendar.YEAR)%> <%=Util.rssClean(copyrightText)%></copyright>
    <generator>IMS Neptune</generator>
    <%
      // level 0
      Node root = new Node(application, 0);
      String url = "index.jsp";
      NodeLink nl = root.getCurrentNodeLink(application);
      Page p = null;
      if (nl!=null && nl.isPage()) {
        p = nl.getPage(application);
    %>
    <item>
      <title><%=Util.rssClean(p.title)%></title>
      <link>http://<%=siteHost%></link>
      <% if (p.metadescription!=null) { %><description><%=Util.rssClean(p.metadescription)%></description><% } %>
      <pubDate><%=pubDateFormat.format(p.lastModified(application))%></pubDate>
      <guid isPermaLink="true">http://<%=siteHost%>/<%=url%></guid>
    </item>
    <%
    }
    // level 1
    NodeListIterator rootIterator = root.getNodeListIterator(application);
    while (rootIterator.hasNext()) {
      Node l1 = rootIterator.nextNode();
      if (l1.isVisible() && (!accessEnabled || au.mayAccess(application,l1))) {
        nl = l1.getCurrentNodeLink(application);
        if (nl!=null && nl.isPage()) {
          url = l1.url;
          if (!url.substring(0,4).toLowerCase().equals("http")) url = "http://"+request.getServerName()+application.getContextPath()+url;
          p = nl.getPage(application);
    %>
    <item>
      <title><%=Util.rssClean(p.title)%></title>
      <category><%=Util.rssClean(l1.nodename)%></category>
      <link><%=url%></link>
      <% if (p.metadescription!=null) { %><description><%=Util.rssClean(p.metadescription)%></description><% } %>
      <pubDate><%=pubDateFormat.format(p.lastModified(application))%></pubDate>
      <guid isPermaLink="true"><%=url%></guid>
    </item>
    <%
    }
    // level 2
    NodeListIterator l1Iterator = l1.getNodeListIterator(application);
    while (l1Iterator.hasNext()) {
      Node l2 = l1Iterator.nextNode();
      if (l2.isVisible() && (!accessEnabled || au.mayAccess(application,l2))) {
        nl = l2.getCurrentNodeLink(application);
        if (nl!=null && nl.isPage()) {
          url = l2.url;
          if (!url.substring(0,4).toLowerCase().equals("http")) url = "http://"+request.getServerName()+application.getContextPath()+url;
          p = nl.getPage(application);
    %>
    <item>
      <title><%=Util.rssClean(p.title)%></title>
      <category><%=Util.rssClean(l2.nodename)%></category>
      <link><%=url%></link>
      <% if (p.metadescription!=null) { %><description><%=Util.rssClean(p.metadescription)%></description><% } %>
      <pubDate><%=pubDateFormat.format(p.lastModified(application))%></pubDate>
      <guid isPermaLink="true"><%=url%></guid>
    </item>
    <%
    }
    // level 3
    NodeListIterator l2Iterator = l2.getNodeListIterator(application);
    while (l2Iterator.hasNext()) {
      Node l3 = l2Iterator.nextNode();
      if (l3.isVisible() && (!accessEnabled || au.mayAccess(application,l3))) {
        nl = l3.getCurrentNodeLink(application);
        if (nl!=null && nl.isPage()) {
          url = l3.url;
          if (!url.substring(0,4).toLowerCase().equals("http")) url = "http://"+request.getServerName()+application.getContextPath()+url;
          p = nl.getPage(application);
    %>
    <item>
      <title><%=Util.rssClean(p.title)%></title>
      <category><%=Util.rssClean(l3.nodename)%></category>
      <link><%=url%></link>
      <% if (p.metadescription!=null) { %><description><%=Util.rssClean(p.metadescription)%></description><% } %>
      <pubDate><%=pubDateFormat.format(p.lastModified(application))%></pubDate>
      <guid isPermaLink="true"><%=url%></guid>
    </item>
    <%
    }
    // level 4
    NodeListIterator l3Iterator = l3.getNodeListIterator(application);
    while (l3Iterator.hasNext()) {
      Node l4 = l3Iterator.nextNode();
      if (l4.isVisible() && (!accessEnabled || au.mayAccess(application,l4))) {
        nl = l4.getCurrentNodeLink(application);
        if (nl!=null && nl.isPage()) {
          url = l4.url;
          if (!url.substring(0,4).toLowerCase().equals("http")) url = "http://"+request.getServerName()+application.getContextPath()+url;
          p = nl.getPage(application);
  %>
    <item>
      <title><%=Util.rssClean(p.title)%></title>
      <category><%=Util.rssClean(l4.nodename)%></category>
      <link><%=url%></link>
      <% if (p.metadescription!=null) { %><description><%=Util.rssClean(p.metadescription)%></description><% } %>
      <pubDate><%=pubDateFormat.format(p.lastModified(application))%></pubDate>
      <guid isPermaLink="true"><%=url%></guid>
    </item>
    <%
    }
  } // if l4 public
} // level 4
} // if level 3 public
} // level 3
} // if level 2 public
} // level 2
} // if level 1 public
} // level 1
    %>
  </channel>
</rss>
